# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tools_extension.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 416)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 0, 781, 161))
        self.tableView.setObjectName("tableView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.statusbar.setAcceptDrops(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.dockWidgetContents_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 791, 221))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.horizontalLayoutWidget)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_2)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 814, 23))
        self.menuBar.setDefaultUp(True)
        self.menuBar.setObjectName("menuBar")
        self.menuoptions = QtWidgets.QMenu(self.menuBar)
        self.menuoptions.setObjectName("menuoptions")
        self.menuview = QtWidgets.QMenu(self.menuBar)
        self.menuview.setObjectName("menuview")
        MainWindow.setMenuBar(self.menuBar)
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.actionsettings = QtWidgets.QAction(MainWindow)
        self.actionsettings.setObjectName("actionsettings")
        self.actionmake_server = QtWidgets.QAction(MainWindow)
        self.actionmake_server.setObjectName("actionmake_server")
        self.actionexit_2 = QtWidgets.QAction(MainWindow)
        self.actionexit_2.setObjectName("actionexit_2")
        self.actiontoolbar = QtWidgets.QAction(MainWindow)
        self.actiontoolbar.setObjectName("actiontoolbar")
        self.actiontools_ext = QtWidgets.QAction(MainWindow)
        self.actiontools_ext.setObjectName("actiontools_ext")
        self.actionstatusbar = QtWidgets.QAction(MainWindow)
        self.actionstatusbar.setObjectName("actionstatusbar")
        self.menuoptions.addAction(self.actionsettings)
        self.menuoptions.addAction(self.actionmake_server)
        self.menuoptions.addSeparator()
        self.menuoptions.addAction(self.actionexit_2)
        self.menuview.addAction(self.actiontoolbar)
        self.menuview.addAction(self.actiontools_ext)
        self.menuview.addAction(self.actionstatusbar)
        self.menuBar.addAction(self.menuoptions.menuAction())
        self.menuBar.addAction(self.menuview.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "日志信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "域名更新"))
        self.menuoptions.setTitle(_translate("MainWindow", "options"))
        self.menuview.setTitle(_translate("MainWindow", "view"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionexit.setText(_translate("MainWindow", "exit"))
        self.actionsettings.setText(_translate("MainWindow", "settings"))
        self.actionmake_server.setText(_translate("MainWindow", "make server"))
        self.actionexit_2.setText(_translate("MainWindow", "exit"))
        self.actiontoolbar.setText(_translate("MainWindow", "toolbar"))
        self.actiontools_ext.setText(_translate("MainWindow", "tools_ext"))
        self.actionstatusbar.setText(_translate("MainWindow", "statusbar"))
